version: '3.7'
services:
  registry:
    image: registry:2.7.1
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_HTTP_HOST=http://127.0.0.1:5000
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_ACCESSKEY=admin
      - REGISTRY_STORAGE_S3_SECRETKEY=password
      - REGISTRY_STORAGE_S3_BUCKET=bucket1
      - REGISTRY_STORAGE_S3_REGION=us-east-1
      - REGISTRY_STORAGE_S3_REGIONENDPOINT="http://s3:9000"
      - REGISTRY_HEALTH_STORAGEDRIVER_ENABLED=false
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_LOG_LEVEL=debug

  s3:
    image: minio/minio:RELEASE.2020-10-03T02-19-42Z
    ports:
      - "9000:9000"
    environment:
        MINIO_ACCESS_KEY: admin
        MINIO_SECRET_KEY: password
    volumes:
        - ./volumes/minio/:/data
    entrypoint: sh
    command: >
        -c 'mkdir -p /data/bucket1
        && /usr/bin/minio server /data'

networks:
  default:
    name: docker-registry-playground
